{
    "PackageVulnerabilityID": "1",
    "DisclosureDate": "2021-01-30",
    "AffectedVersionRange": "*",
    "Summary": "Arbitrary Code Execution",
    "Contributor": {
        "Discloser": "43377443",
        "Fixer": "61599526"
    },
    "Package": {
        "Registry": "pip",
        "Name": "gita",
        "URL": "https://pypi.org/project/gita",
        "Downloads": "104"
    },
    "CWEs": [
        {
            "ID": "94",
            "Description": "Arbitrary Code Execution"
        }
    ],
    "CVSS": {
        "Version": "3.1",
        "AV": "P",
        "AC": "H",
        "PR": "L",
        "UI": "N",
        "S": "U",
        "C": "L",
        "I": "L",
        "A": "L",
        "E": "",
        "RL": "",
        "RC": "",
        "Score": "3.8"
    },
    "CVEs": [
        ""
    ],
    "Repository": {
        "URL": "https://github.com/nosarthur/gita",
        "Codebase": [
            "Python"
        ],
        "Owner": "nosarthur",
        "Name": "gita",
        "Forks": "43",
        "Stars": "859",
        "ForkName": "gita"
    },
    "Permalinks": [
        "https://github.com/nosarthur/gita/blob/master/gita/utils.py#L244"
    ],
    "References": [
        {
            "Description": "",
            "URL": ""
        }
    ],
    "PrNumber": "1810"
}