{
    "PackageVulnerabilityID": "1",
    "DisclosureDate": "2021-01-28",
    "AffectedVersionRange": "*",
    "Summary": "Arbitrary Code Execution",
    "Contributor": {
        "Discloser": "61599526",
        "Fixer": ""
    },
    "Package": {
        "Registry": "pip",
        "Name": "tfx",
        "URL": "https://pypi.org/project/tfx",
        "Downloads": "23629"
    },
    "CWEs": [
        {
            "ID": "94",
            "Description": "Arbitrary Code Execution"
        }
    ],
    "CVSS": {
        "Version": "3.1",
        "AV": "",
        "AC": "",
        "PR": "",
        "UI": "",
        "S": "",
        "C": "",
        "I": "",
        "A": "",
        "E": "",
        "RL": "",
        "RC": "",
        "Score": "8.5"
    },
    "CVEs": [
        ""
    ],
    "Repository": {
        "URL": "https://github.com/tensorflow/tfx",
        "Codebase": [
            "Python"
        ],
        "Owner": "tensorflow",
        "Name": "tfx",
        "Forks": "390",
        "Stars": "1296"
    },
    "Permalinks": [
        "https://drive.google.com/file/d/1M8OVLlrnrmujCWmq5zmRGxXRAyJCSWxq/view?usp=sharing"
    ],
    "References": [
        {
            "Description": "",
            "URL": ""
        }
    ],
    "PrNumber": "1803",
    "FixSubmissionCount": 1
}