{
    "PackageVulnerabilityID": "1",
    "DisclosureDate": "2021-01-07",
    "AffectedVersionRange": "*",
    "Summary": "Arbitrary Code Execution",
    "Contributor": {
        "Discloser": "61599526",
        "Fixer": "43377443"
    },
    "Package": {
        "Registry": "pip",
        "Name": "aiocache",
        "URL": "https://pypi.org/project/aiocache",
        "Downloads": "4981"
    },
    "CWEs": [
        {
            "ID": "94",
            "Description": "Arbitrary Code Execution"
        }
    ],
    "CVSS": {
        "Version": "3.1",
        "AV": "P",
        "AC": "H",
        "PR": "L",
        "UI": "N",
        "S": "U",
        "C": "L",
        "I": "L",
        "A": "L",
        "E": "",
        "RL": "",
        "RC": "",
        "Score": "3.8"
    },
    "CVEs": [
        ""
    ],
    "Repository": {
        "URL": "https://github.com/aio-libs/aiocache",
        "Codebase": [
            "Python"
        ],
        "Owner": "aio-libs",
        "Name": "aiocache",
        "Forks": "73",
        "Stars": "484",
        "ForkName": "aiocache"
    },
    "Permalinks": [
        "https://drive.google.com/file/d/1Zf-OEiLoDx4wEDabElhWaW1AQgVG5bAO/view?usp=sharing"
    ],
    "References": [
        {
            "Description": "",
            "URL": ""
        }
    ],
    "PrNumber": "1493",
    "FixSubmissionCount": 1
}