{
    "PackageVulnerabilityID": "1",
    "DisclosureDate": "2021-01-31",
    "AffectedVersionRange": "*",
    "Summary": "Arbitrary Code Execution",
    "Contributor": {
        "Discloser": "61599526",
        "Fixer": ""
    },
    "Package": {
        "Registry": "pip",
        "Name": "faust",
        "URL": "https://pypi.org/project/faust",
        "Downloads": "23107"
    },
    "CWEs": [
        {
            "ID": "CWE-94",
            "Description": "Arbitrary Code Execution"
        }
    ],
    "CVSS": {
        "Version": "3.1",
        "AV": "",
        "AC": "",
        "PR": "",
        "UI": "",
        "S": "",
        "C": "",
        "I": "",
        "A": "",
        "E": "",
        "RL": "",
        "RC": "",
        "Score": "8.3"
    },
    "CVEs": [
        ""
    ],
    "Repository": {
        "URL": "https://github.com/robinhood/faust",
        "Codebase": [
            "Python"
        ],
        "Owner": "robinhood",
        "Name": "faust",
        "Forks": "438",
        "Stars": "5263"
    },
    "Permalinks": [
        "https://drive.google.com/file/d/15cTqhVLg5lnmUDTAvuTKAZUoevUy-T-B/view?usp=sharing"
    ],
    "References": [
        {
            "Description": "",
            "URL": ""
        }
    ],
    "PrNumber": "1587",
    "FixSubmissionCount": 1
}